### ISSUE TITLE
How to hookup onChange event? 

### ISSUE THREAD

**Issue by stensalweb** [Hallo89/Slider89#3]
The design is very neat, but I cannot figure out how to hook up onChange event.  Do you have any sample code for this?

**Comment by Maluscat** [comment]
Do you use the new in-development rewritten version (default branch `project-rewrite`) or the stale one (`master`/`gh-pages`)?
I'm surprised to see someone trying my library, thanks :D

**Comment by Maluscat** [comment]
Feel free to open this issue back up in case of questions!
